from pydantic import BaseModel
from typing import Dict, Any

def get_clean_schema(model: type[BaseModel]) -> Dict[str, Any]:
    """
    Generates a JSON schema from a Pydantic model and removes fields
    like 'default' and 'title' which are not supported by the Gemini API's
    JSON schema validation parser.
    """
    schema = model.model_json_schema()
    
    def clean_schema_element(element: Any) -> Any:
        if isinstance(element, dict):
            # Resolve 'anyOf' union types (generated by Pydantic for Optional/nullable fields)
            # into a single non-null type schema that the Gemini API supports.
            if "anyOf" in element:
                any_of_list = element["anyOf"]
                non_null_item = None
                for item in any_of_list:
                    if isinstance(item, dict) and item.get("type") != "null":
                        non_null_item = item
                        break
                if non_null_item:
                    return clean_schema_element(non_null_item)
                elif any_of_list:
                    return clean_schema_element(any_of_list[0])

            # Strip out 'default' and 'title' keys which trigger Gemini validation errors
            return {
                k: clean_schema_element(v) 
                for k, v in element.items() 
                if k not in ["default", "title"]
            }
        elif isinstance(element, list):
            return [clean_schema_element(item) for item in element]
        return element

    return clean_schema_element(schema)
